#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x4F494A942E4616C2 (bruno@clisp.org)
#
Name     : gettext
Version  : 0.20.1
Release  : 32
URL      : https://mirrors.kernel.org/gnu/gettext/gettext-0.20.1.tar.xz
Source0  : https://mirrors.kernel.org/gnu/gettext/gettext-0.20.1.tar.xz
Source1  : https://mirrors.kernel.org/gnu/gettext/gettext-0.20.1.tar.xz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0 GPL-3.0 GPL-3.0+ LGPL-2.0+ LGPL-2.1 MIT
Requires: gettext-bin = %{version}-%{release}
Requires: gettext-data = %{version}-%{release}
Requires: gettext-info = %{version}-%{release}
Requires: gettext-lib = %{version}-%{release}
Requires: gettext-license = %{version}-%{release}
Requires: gettext-locales = %{version}-%{release}
Requires: gettext-man = %{version}-%{release}
BuildRequires : acl-dev
BuildRequires : bison
BuildRequires : emacs
BuildRequires : glib-dev
BuildRequires : glibc-locale
BuildRequires : libcroco-dev
BuildRequires : libtool-dev
BuildRequires : libunistring-dev
BuildRequires : libxml2-dev
BuildRequires : ncurses-dev
Patch1: 0001-Fix-autoconf-tests-for-lto.patch

%description
This is the GNU gettext package.  It is interesting for authors or
maintainers of other packages or programs which they want to see
internationalized.  As one step the handling of messages in different
languages should be implemented.  For this task GNU gettext provides
the needed tools and library functions.

%package bin
Summary: bin components for the gettext package.
Group: Binaries
Requires: gettext-data = %{version}-%{release}
Requires: gettext-license = %{version}-%{release}

%description bin
bin components for the gettext package.


%package data
Summary: data components for the gettext package.
Group: Data

%description data
data components for the gettext package.


%package dev
Summary: dev components for the gettext package.
Group: Development
Requires: gettext-lib = %{version}-%{release}
Requires: gettext-bin = %{version}-%{release}
Requires: gettext-data = %{version}-%{release}
Provides: gettext-devel = %{version}-%{release}
Requires: gettext = %{version}-%{release}

%description dev
dev components for the gettext package.


%package doc
Summary: doc components for the gettext package.
Group: Documentation
Requires: gettext-man = %{version}-%{release}
Requires: gettext-info = %{version}-%{release}

%description doc
doc components for the gettext package.


%package info
Summary: info components for the gettext package.
Group: Default

%description info
info components for the gettext package.


%package lib
Summary: lib components for the gettext package.
Group: Libraries
Requires: gettext-data = %{version}-%{release}
Requires: gettext-license = %{version}-%{release}

%description lib
lib components for the gettext package.


%package license
Summary: license components for the gettext package.
Group: Default

%description license
license components for the gettext package.


%package locales
Summary: locales components for the gettext package.
Group: Default

%description locales
locales components for the gettext package.


%package man
Summary: man components for the gettext package.
Group: Default

%description man
man components for the gettext package.


%prep
%setup -q -n gettext-0.20.1
cd %{_builddir}/gettext-0.20.1
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1583358564
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 -fstack-protector-strong -mzero-caller-saved-regs=used "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 -fstack-protector-strong -mzero-caller-saved-regs=used "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 -fstack-protector-strong -mzero-caller-saved-regs=used "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 -fstack-protector-strong -mzero-caller-saved-regs=used "
%reconfigure --disable-static
make

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 check || :

%install
export SOURCE_DATE_EPOCH=1583358564
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/gettext
cp %{_builddir}/gettext-0.20.1/COPYING %{buildroot}/usr/share/package-licenses/gettext/0dd432edfab90223f22e49c02e2124f87d6f0a56
cp %{_builddir}/gettext-0.20.1/gettext-runtime/COPYING %{buildroot}/usr/share/package-licenses/gettext/b50e61b44f348769338def2b672f3bda98a9680b
cp %{_builddir}/gettext-0.20.1/gettext-runtime/intl/COPYING.LIB %{buildroot}/usr/share/package-licenses/gettext/66c77efd1cf9c70d4f982ea59487b2eeb6338e26
cp %{_builddir}/gettext-0.20.1/gettext-runtime/libasprintf/COPYING %{buildroot}/usr/share/package-licenses/gettext/54160ca9affa68b0cb83be6f41c35efc194deb0c
cp %{_builddir}/gettext-0.20.1/gettext-runtime/libasprintf/COPYING.LIB %{buildroot}/usr/share/package-licenses/gettext/66c77efd1cf9c70d4f982ea59487b2eeb6338e26
cp %{_builddir}/gettext-0.20.1/gettext-tools/COPYING %{buildroot}/usr/share/package-licenses/gettext/e04ee5ef8864b1ad305b660ddfd653b86bea6975
cp %{_builddir}/gettext-0.20.1/gettext-tools/gnulib-lib/libxml/COPYING %{buildroot}/usr/share/package-licenses/gettext/3c21506a45e8d0171fc92fd4ff6903c13adde660
cp %{_builddir}/gettext-0.20.1/gnulib-local/lib/libxml/COPYING %{buildroot}/usr/share/package-licenses/gettext/3c21506a45e8d0171fc92fd4ff6903c13adde660
cp %{_builddir}/gettext-0.20.1/libtextstyle/COPYING %{buildroot}/usr/share/package-licenses/gettext/0dd432edfab90223f22e49c02e2124f87d6f0a56
cp %{_builddir}/gettext-0.20.1/libtextstyle/lib/libxml/COPYING %{buildroot}/usr/share/package-licenses/gettext/3c21506a45e8d0171fc92fd4ff6903c13adde660
%make_install
%find_lang gettext-runtime
%find_lang gettext-tools
## install_append content
# drop all files with '+' in it, borks the updater
rm -rf %{buildroot}/usr/share/doc/gettext/examples/hello-c++*
## install_append end

%files
%defattr(-,root,root,-)
/usr/lib64/gettext/cldr-plurals
/usr/lib64/gettext/hostname
/usr/lib64/gettext/project-id
/usr/lib64/gettext/urlget
/usr/lib64/gettext/user-email

%files bin
%defattr(-,root,root,-)
/usr/bin/autopoint
/usr/bin/envsubst
/usr/bin/gettext
/usr/bin/gettext.sh
/usr/bin/gettextize
/usr/bin/msgattrib
/usr/bin/msgcat
/usr/bin/msgcmp
/usr/bin/msgcomm
/usr/bin/msgconv
/usr/bin/msgen
/usr/bin/msgexec
/usr/bin/msgfilter
/usr/bin/msgfmt
/usr/bin/msggrep
/usr/bin/msginit
/usr/bin/msgmerge
/usr/bin/msgunfmt
/usr/bin/msguniq
/usr/bin/ngettext
/usr/bin/recode-sr-latin
/usr/bin/xgettext

%files data
%defattr(-,root,root,-)
/usr/share/emacs/site-lisp/po-compat.el
/usr/share/emacs/site-lisp/po-compat.elc
/usr/share/emacs/site-lisp/po-mode.el
/usr/share/emacs/site-lisp/po-mode.elc
/usr/share/emacs/site-lisp/start-po.el
/usr/share/emacs/site-lisp/start-po.elc
/usr/share/gettext-0.20/its/glade.loc
/usr/share/gettext-0.20/its/glade1.its
/usr/share/gettext-0.20/its/glade2.its
/usr/share/gettext-0.20/its/gsettings.its
/usr/share/gettext-0.20/its/gsettings.loc
/usr/share/gettext-0.20/its/gtkbuilder.its
/usr/share/gettext-0.20/its/metainfo.its
/usr/share/gettext-0.20/its/metainfo.loc
/usr/share/gettext/ABOUT-NLS
/usr/share/gettext/archive.dir.tar.xz
/usr/share/gettext/config.rpath
/usr/share/gettext/gettext.h
/usr/share/gettext/javaversion.class
/usr/share/gettext/msgunfmt.tcl
/usr/share/gettext/po/Makefile.in.in
/usr/share/gettext/po/Makevars.template
/usr/share/gettext/po/Rules-quot
/usr/share/gettext/po/boldquot.sed
/usr/share/gettext/po/en@boldquot.header
/usr/share/gettext/po/en@quot.header
/usr/share/gettext/po/insert-header.sin
/usr/share/gettext/po/quot.sed
/usr/share/gettext/po/remove-potcdate.sin
/usr/share/gettext/projects/GNOME/team-address
/usr/share/gettext/projects/GNOME/teams.html
/usr/share/gettext/projects/GNOME/teams.url
/usr/share/gettext/projects/GNOME/trigger
/usr/share/gettext/projects/KDE/team-address
/usr/share/gettext/projects/KDE/teams.html
/usr/share/gettext/projects/KDE/teams.url
/usr/share/gettext/projects/KDE/trigger
/usr/share/gettext/projects/TP/team-address
/usr/share/gettext/projects/TP/teams.html
/usr/share/gettext/projects/TP/teams.url
/usr/share/gettext/projects/TP/trigger
/usr/share/gettext/projects/index
/usr/share/gettext/projects/team-address
/usr/share/gettext/styles/po-default.css
/usr/share/gettext/styles/po-emacs-x.css
/usr/share/gettext/styles/po-emacs-xterm.css
/usr/share/gettext/styles/po-emacs-xterm16.css
/usr/share/gettext/styles/po-emacs-xterm256.css
/usr/share/gettext/styles/po-vim.css

%files dev
%defattr(-,root,root,-)
/usr/include/autosprintf.h
/usr/include/gettext-po.h
/usr/include/textstyle.h
/usr/include/textstyle/stdbool.h
/usr/include/textstyle/version.h
/usr/include/textstyle/woe32dll.h
/usr/lib64/libasprintf.so
/usr/lib64/libgettextlib-0.20.1.so
/usr/lib64/libgettextlib.so
/usr/lib64/libgettextpo.so
/usr/lib64/libgettextsrc-0.20.1.so
/usr/lib64/libgettextsrc.so
/usr/lib64/libtextstyle.so
/usr/lib64/preloadable_libintl.so
/usr/share/aclocal/*.m4
/usr/share/man/man3/bind_textdomain_codeset.3
/usr/share/man/man3/bindtextdomain.3
/usr/share/man/man3/dcgettext.3
/usr/share/man/man3/dcngettext.3
/usr/share/man/man3/dgettext.3
/usr/share/man/man3/dngettext.3
/usr/share/man/man3/gettext.3
/usr/share/man/man3/ngettext.3
/usr/share/man/man3/textdomain.3

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/gettext/*
/usr/share/doc/libasprintf/autosprintf_all.html
/usr/share/doc/libtextstyle/libtextstyle_1.html
/usr/share/doc/libtextstyle/libtextstyle_2.html
/usr/share/doc/libtextstyle/libtextstyle_3.html
/usr/share/doc/libtextstyle/libtextstyle_4.html
/usr/share/doc/libtextstyle/libtextstyle_5.html
/usr/share/doc/libtextstyle/libtextstyle_6.html
/usr/share/doc/libtextstyle/libtextstyle_7.html
/usr/share/doc/libtextstyle/libtextstyle_abt.html
/usr/share/doc/libtextstyle/libtextstyle_toc.html

%files info
%defattr(0644,root,root,0755)
/usr/share/info/autosprintf.info
/usr/share/info/gettext.info
/usr/share/info/libtextstyle.info

%files lib
%defattr(-,root,root,-)
/usr/lib64/libasprintf.so.0
/usr/lib64/libasprintf.so.0.0.0
/usr/lib64/libgettextpo.so.0
/usr/lib64/libgettextpo.so.0.5.5
/usr/lib64/libtextstyle.so.0
/usr/lib64/libtextstyle.so.0.0.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/gettext/0dd432edfab90223f22e49c02e2124f87d6f0a56
/usr/share/package-licenses/gettext/3c21506a45e8d0171fc92fd4ff6903c13adde660
/usr/share/package-licenses/gettext/54160ca9affa68b0cb83be6f41c35efc194deb0c
/usr/share/package-licenses/gettext/66c77efd1cf9c70d4f982ea59487b2eeb6338e26
/usr/share/package-licenses/gettext/b50e61b44f348769338def2b672f3bda98a9680b
/usr/share/package-licenses/gettext/e04ee5ef8864b1ad305b660ddfd653b86bea6975

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/autopoint.1
/usr/share/man/man1/envsubst.1
/usr/share/man/man1/gettext.1
/usr/share/man/man1/gettextize.1
/usr/share/man/man1/msgattrib.1
/usr/share/man/man1/msgcat.1
/usr/share/man/man1/msgcmp.1
/usr/share/man/man1/msgcomm.1
/usr/share/man/man1/msgconv.1
/usr/share/man/man1/msgen.1
/usr/share/man/man1/msgexec.1
/usr/share/man/man1/msgfilter.1
/usr/share/man/man1/msgfmt.1
/usr/share/man/man1/msggrep.1
/usr/share/man/man1/msginit.1
/usr/share/man/man1/msgmerge.1
/usr/share/man/man1/msgunfmt.1
/usr/share/man/man1/msguniq.1
/usr/share/man/man1/ngettext.1
/usr/share/man/man1/recode-sr-latin.1
/usr/share/man/man1/xgettext.1

%files locales -f gettext-runtime.lang -f gettext-tools.lang
%defattr(-,root,root,-)

